### ISSUE TITLE
Changing the ammount of ram

### ISSUE THREAD

**Issue by Jtanner5674** [0n1udra/slime_server#6]
How do I allocate mor then 2g to the server? I have 8gs on the machine im running it on and want to allocate them as well.

**Comment by 0n1udra** [comment]
In `slime_vars.py` edit the `server_list` dictionary.
 Format is: `{'server name': ['server name', 'description', 'java launch command']}`.
 E.g. `{'papermc': ['papermc', 'Lightweight PaperMC.', 'java -Xmx3G -Xms1G -jar server.jar nogui']}`. 

`-Xmx3G` is that max allocated RAM, and `-Xms1G` is the minimum.  
For my setup I have different minecraft servers I want to switch back and forth with, each with their own backup folders and unique launch commands. This does not mean you can run multiple servers at once with the bot, it's just a way to manage separate minecraft server folders.  

Make sure `mc_path` variable is set. This is where the server folder and it's backup folders will go. E.g. `/home/USER/Games/Minecraft/`. My PaperMC jar location will be  `/home/USER/Games/Minecraft/papermc/server.jar`. I also have a vanilla server: `/home/USER/Games/Minecraft/vanilla/server.jar` etc etc.
Backups for PaperMC server will go in `/home/USER/Games/Minecraft/world_backups/papermc/`.

You can also set the default when the bot launches by editing `server_selected` variable, e.g. `server_selected = server_list['papermc']`

Once the bot is launched. Use `?serverselect`/`?sselect` to select the server you want to control. E.g. `?sselect papermc`.

Sorry for the confusion. I will see if there's better ways soon, and write up proper documentation on how to set up everything. I haven't been able to update this one recently because of other projects.

Here is my setup:
![Screenshot-20220720102408-1613x408](https://user-images.githubusercontent.com/15573136/180007108-17533ed0-4084-4e16-89f5-8e20c8db3fe0.png)
Since a few of my servers use the same java command I use f-strings.
