### ISSUE TITLE
Discord-Components give me error

### ISSUE THREAD

**Issue by Gonaaal** [0n1udra/slime_server#8]
![image](https://user-images.githubusercontent.com/87767165/184324812-b07322c5-1b15-47d1-876e-997284322899.png)
![image](https://user-images.githubusercontent.com/87767165/184324848-2d8d5abd-020b-4dc9-a565-e40e64d24396.png)

**Comment by 0n1udra** [comment]
Is this trying to install the latest version or the version from requirements.txt. I would try installing the latest version 'pip3 install discord-conponents'.

**Comment by gamingoninsulin** [comment]
i have the same error but did the pip3 thing but still notting to download i even tryed pipwin but that says not found

**Comment by 0n1udra** [comment]
Things are starting to break down due to discord.py and discord-components are now deprecated, more info below. 

Here is a quick fix (hopefully) for now.
1. Download discrord.py-components repository here: https://github.com/kiki7000/discord.py-components.git
2. Activated venv (if using one). Make sure discord.py is installed beforehand.
3. Go into the discord.py-components folder where setup.py is. 
4. Run `python3 setup.py install`.

If need to install discord.py also: https://github.com/Rapptz/discord.py.git

I am planning on doing a major update to slime_server, to add slash commands, and to use a more update to date discord python library, like possibly Pycord. If anyone has suggestions, lmk pls.

What happened to discord.py: https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1

**Comment by Gonaaal** [comment]
![image](https://user-images.githubusercontent.com/87767165/184838956-72513e64-18f0-4540-98a5-33659da86bef.png)
I have install via git clone discord.pu and discord.py-components

**Comment by 0n1udra** [comment]
@Gonaaal I am still trying to figure out your specific issue on my Windows 10 VM. But for now, if you want, you can try out the early version of the pycord update.

Download, git clone, change the branch to pycord: https://github.com/0n1udra/slime_server/tree/pycord
It's still very new and not very stable, haven't tested everything to make sure they all work. But it might work better than what you have now. 

Create a new venv, and install the `requirments.txt`.

**Comment by 0n1udra** [comment]
Still working on finding the issue with your setup. But in the meantime, you can try out the new pycord update and see if that works instead. 

Either make a new venv for this branch, or uninstall discord.py and discord-components before installing pycord library.
Download, git clone, or change branch to pycord.
https://github.com/0n1udra/slime_server/tree/pycord

Still highly unstable. Have not tested everything. E.g. some control panels will not work. But prefix commands should work the same (hopefully).

**Comment by Gonaaal** [comment]
Ok, thanks and or do you know how to create it in js?

**Comment by 0n1udra** [comment]
no, I'm not experienced in javascript at all, except for some very basics. I am not planning on it either for now.

**Comment by 0n1udra** [comment]
I think (I hope) the disocrd.py 2.0 branch is somewhat usable now. I transitioned the buttons and selection components to discord.py 2.0. More people testing this out would be great. And once I'm more confident, I'll merge this into the main branch. Once that happens, using older discord.py version with discord-components will still be available on the discord-components branch.
